from django.db import models


class GenderChoices(models.TextChoices):
    MALE = "M", "Male"
    FEMALE = "F", "Female"
    UNKNOWN = "U", "Unknown"


class CountryChoices(models.TextChoices):
    USA = "US", "United States"
    CANADA = "CA", "Canada"
    UK = "GB", "United Kingdom"
    AUSTRALIA = "AU", "Australia"
    GERMANY = "DE", "Germany"
    FRANCE = "FR", "France"
    JAPAN = "JP", "Japan"
    CHINA = "CN", "China"
    INDIA = "IN", "India"
    BRAZIL = "BR", "Brazil"
    RUSSIA = "RU", "Russia"
    SOUTH_KOREA = "KR", "South Korea"
    ITALY = "IT", "Italy"
    SPAIN = "ES", "Spain"
    MEXICO = "MX", "Mexico"
    NETHERLANDS = "NL", "Netherlands"
    SWITZERLAND = "CH", "Switzerland"
    SWEDEN = "SE", "Sweden"
    NORWAY = "NO", "Norway"
    FINLAND = "FI", "Finland"
    DENMARK = "DK", "Denmark"
    BELGIUM = "BE", "Belgium"
    AUSTRIA = "AT", "Austria"
    IRELAND = "IE", "Ireland"
    NEW_ZEALAND = "NZ", "New Zealand"
    SOUTH_AFRICA = "ZA", "South Africa"
    ARGENTINA = "AR", "Argentina"
    CHILE = "CL", "Chile"
    COLOMBIA = "CO", "Colombia"
    PERU = "PE", "Peru"
    POLAND = "PL", "Poland"
    PORTUGAL = "PT", "Portugal"
    GREECE = "GR", "Greece"
    TURKEY = "TR", "Turkey"
    SAUDI_ARABIA = "SA", "Saudi Arabia"
    UNITED_ARAB_EMIRATES = "AE", "United Arab Emirates"
    ISRAEL = "IL", "Israel"
    SINGAPORE = "SG", "Singapore"
    MALAYSIA = "MY", "Malaysia"
    THAILAND = "TH", "Thailand"
    INDONESIA = "ID", "Indonesia"
    PHILIPPINES = "PH", "Philippines"
    VIETNAM = "VN", "Vietnam"
    PAKISTAN = "PK", "Pakistan"
    BANGLADESH = "BD", "Bangladesh"
    EGYPT = "EG", "Egypt"
    NIGERIA = "NG", "Nigeria"
    KENYA = "KE", "Kenya"
    GHANA = "GH", "Ghana"
    TANZANIA = "TZ", "Tanzania"
    NEPAL = "NP", "Nepal"
    OTHERS = "OO", "Others"


class StateChoices(models.TextChoices):
    ALABAMA = "AL", "Alabama"
    ALASKA = "AK", "Alaska"
    ARIZONA = "AZ", "Arizona"
    ARKANSAS = "AR", "Arkansas"
    CALIFORNIA = "CA", "California"
    COLORADO = "CO", "Colorado"
    CONNECTICUT = "CT", "Connecticut"
    DELAWARE = "DE", "Delaware"
    FLORIDA = "FL", "Florida"
    GEORGIA = "GA", "Georgia"
    HAWAII = "HI", "Hawaii"
    IDAHO = "ID", "Idaho"
    ILLINOIS = "IL", "Illinois"
    INDIANA = "IN", "Indiana"
    IOWA = "IA", "Iowa"
    KANSAS = "KS", "Kansas"
    KENTUCKY = "KY", "Kentucky"
    LOUISIANA = "LA", "Louisiana"
    MAINE = "ME", "Maine"
    MARYLAND = "MD", "Maryland"
    MASSACHUSETTS = "MA", "Massachusetts"
    MICHIGAN = "MI", "Michigan"
    MINNESOTA = "MN", "Minnesota"
    MISSISSIPPI = "MS", "Mississippi"
    MISSOURI = "MO", "Missouri"
    MONTANA = "MT", "Montana"
    NEBRASKA = "NE", "Nebraska"
    NEVADA = "NV", "Nevada"
    NEW_HAMPSHIRE = "NH", "New Hampshire"
    NEW_JERSEY = "NJ", "New Jersey"
    NEW_MEXICO = "NM", "New Mexico"
    NEW_YORK = "NY", "New York"
    NORTH_CAROLINA = "NC", "North Carolina"
    NORTH_DAKOTA = "ND", "North Dakota"
    OHIO = "OH", "Ohio"
    OKLAHOMA = "OK", "Oklahoma"
    OREGON = "OR", "Oregon"
    PENNSYLVANIA = "PA", "Pennsylvania"
    RHODE_ISLAND = "RI", "Rhode Island"
    SOUTH_CAROLINA = "SC", "South Carolina"
    SOUTH_DAKOTA = "SD", "South Dakota"
    TENNESSEE = "TN", "Tennessee"
    TEXAS = "TX", "Texas"
    UTAH = "UT", "Utah"
    VERMONT = "VT", "Vermont"
    VIRGINIA = "VA", "Virginia"
    WASHINGTON = "WA", "Washington"
    WEST_VIRGINIA = "WV", "West Virginia"
    WISCONSIN = "WI", "Wisconsin"
    WYOMING = "WY", "Wyoming"
    AMERICAN_SAMOA = "AS", "American Samoa"
    DISTRICT_OF_COLUMBIA = "DC", "District of Columbia"
    FEDERATED_STATES_OF_MICRONESIA = "FM", "Federated States of Micronesia"
    GUAM = "GU", "Guam"
    MARSHALL_ISLANDS = "MH", "Marshall Islands"
    NORTHERN_MARIANA_ISLANDS = "MP", "Northern Mariana Islands"
    PALAU = "PW", "Palau"
    PUERTO_RICO = "PR", "Puerto Rico"
    VIRGIN_ISLANDS = "VI", "Virgin Islands"
    OTHERS = "OO", "Others"


class RegionChoices(models.TextChoices):
    NORTHWEST = "NW", "Northwest"
    NORTHEAST = "NE", "Northeast"
    MIDWEST = "MW", "Midwest"
    SOUTHWEST = "SW", "Southwest"
    SOUTHEAST = "SE", "Southeast"
    WEST = "W", "West"
    EAST = "E", "East"
    NORTH = "N", "North"
    SOUTH = "S", "South"
    CENTRAL = "C", "Central"
    OTHERS = "OO", "Others"


class SiteThemeChoices(models.TextChoices):
    LIGHT = "L", "Light"
    DARK = "D", "Dark"
    SYSTEM = "S", "System"


class FileExtensionChoices(models.TextChoices):
    PDF = "pdf", "PDF"
    DOC = "doc", "DOC"
    DOCX = "docx", "DOCX"
    ODT = "odt", "ODT"
    TXT = "txt", "TXT"
    MD = "md", "MD"
    CSV = "csv", "CSV"
    XLS = "xls", "XLS"
    XLSX = "xlsx", "XLSX"
    ODS = "ods", "ODS"
    PPT = "ppt", "PPT"
    PPTX = "pptx", "PPTX"
    HTML = "html", "HTML"
    HTM = "htm", "HTM"
    JPG = "jpg", "JPG"
    JPEG = "jpeg", "JPEG"
    PNG = "png", "PNG"
    BMP = "bmp", "BMP"
    SVG = "svg", "SVG"
