# Generated by Django 5.0.6 on 2024-11-18 14:03

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substation',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SubstationLMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('energy', models.FloatField(blank=True, help_text='Energy LMP ($/MWh)', null=True)),
                ('congestion', models.FloatField(blank=True, help_text='Congestion LMP ($/MWh)', null=True)),
                ('loss', models.FloatField(blank=True, help_text='Loss LMP ($/MWh)', null=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substation.substation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
