# Generated by Django 5.0.6 on 2024-11-22 06:03

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0002_substation_code_substationlmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('voltage', models.FloatField(help_text='Voltage (kV)')),
                ('utility_area', models.CharField(blank=True, max_length=255, null=True)),
                ('circuit', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_coordinates', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='LineString (Longitude Latitude)', null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='substation',
            name='geo_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Longitude Latitude', null=True, srid=4326),
        ),
    ]
