# Generated by Django 5.0.6 on 2024-11-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0003_transmissionline_alter_substation_geo_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='substationlmp',
            name='market',
            field=models.CharField(choices=[('DAM', 'Day-Ahead Market'), ('RTM_5min', 'Real-Time Market (5-min)')], default='DAM', max_length=50),
        ),
    ]
