# Generated by Django 5.0.6 on 2024-12-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0004_substationlmp_market'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='substation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='substation',
            name='type',
            field=models.CharField(choices=[('transmission', 'Transmission'), ('distribution', 'Distribution')], default='transmission', max_length=50),
        ),
        migrations.AlterField(
            model_name='substation',
            name='voltage',
            field=models.FloatField(blank=True, help_text='Voltage (kV)', null=True),
        ),
        migrations.AddConstraint(
            model_name='substation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'transmission')), fields=('name', 'voltage', 'type', 'interconnecting_entity'), name='unique_transmission_substation'),
        ),
        migrations.AddConstraint(
            model_name='substation',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'transmission'), _negated=True), fields=('name', 'type', 'interconnecting_entity'), name='unique_non_transmission_substation'),
        ),
    ]
