# Generated by Django 5.0.6 on 2025-01-06 14:33

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substation', '0005_alter_substation_unique_together_substation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageLMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('type', models.CharField(choices=[('forecast', 'Forecast'), ('actual', 'Actual')], default='forecast', max_length=50)),
                ('energy', models.FloatField(blank=True, help_text='Energy LMP ($/MWh)', null=True)),
                ('congestion', models.FloatField(blank=True, help_text='Congestion LMP ($/MWh)', null=True)),
                ('loss', models.FloatField(blank=True, help_text='Loss LMP ($/MWh)', null=True)),
                ('total_lmp', models.FloatField(blank=True, help_text='LMP ($/MWh)', null=True)),
                ('opening_price', models.FloatField(blank=True, help_text='Opening Price ($/MWh)', null=True)),
                ('closing_price', models.FloatField(blank=True, help_text='Closing Price ($/MWh)', null=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substation.substation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
