# Generated by Django 5.0.6 on 2024-10-30 10:27

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        CreateExtension("postgis"),
    ]
