# Generated by Django 5.0.6 on 2025-01-09 05:55

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('subscribe_to_newsletter', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('demo', 'Demo'), ('enquiry', 'Enquiry'), ('feedback', 'Feedback')], default='enquiry', max_length=20)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.AddField(
            model_name='appsetting',
            name='admin_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, null=True, size=None, verbose_name='admin emails'),
        ),
    ]
