# Generated by Django 5.0.6 on 2025-01-14 06:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactus_appsetting_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/', validators=[core.validators.validate_image]),
        ),
    ]
